

<script>
//function updateCity() {
    //var countryId = $('billing:country_id').getValue();
    alert('countryId');
    // var numUpdate = $('num_update').getValue();

    // new Ajax.Request("<?php echo $this->getUrl('shippingcity/city/list'); ?>", {
    //             parameters: {
    //                 isAjax: 1, 
    //                 method: 'POST',
    //                 hashtags : hashtags,
    //                 numupdate : numUpdate
    //             },
    //             onSuccess: function(transport) {

    //                 try{
    //                     response = eval('(' + transport.responseText + ')');
                        
    //                 } catch (e) {
    //                     response = {};
    //                 }
    //                 if (response.err) {
    //                     alert("<?php echo $this->jsQuoteEscape($this->__('An error occured. Make sure you are authenticated with Instagram.')); ?>");
    //                 }
    //                 if (response.success) {
    //                     $('content-images').replace('<div id="content-images"></div>');
    //                     $('content-images').insert(response.data);
    //                 } else {
    //                     var msg = response.error_messages;
    //                     if (typeof(msg)=='object') {
    //                         msg = msg.join("\n");
    //                     }
    //                     if (msg) {
    //                         $('review-please-wait').hide();
    //                         alert(msg);
    //                         return;
    //                     }
    //                 }
    //                 $('review-please-wait').hide();
    //                 alert("<?php echo $this->jsQuoteEscape($this->__('Unknown Error. Please try again later.')); ?>");
    //                 return;
    //             },
    //             onFailure: function(){
    //                 alert("<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')) ?>");
    //                 $('review-please-wait').hide();
    //             }
    //         });
    //         return false;
    //     }
</script>